//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GbService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("frzekfksd~~#{uhgvge``\\rfd67481+56r\']@\\rfçè-t-\'éèça)àoiçàaezdc")]
        public string CypherPassword {
            get {
                return ((string)(this["CypherPassword"]));
            }
            set {
                this["CypherPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{""Exponent"":""AQAB"",""Modulus"":""sHIPKf6689Iok1J8k3VLUwdnmUeo23QefdGRorCUCaZ+UKwQWPIGM2N+CWmwdO2yIv4dwAPOz7sibPXC/coTzwLjY1IH0MVzpkdbUgmzZXWJH5h6dVEmin9OSI0dJmEruVhNaMOt0IGkrJ8sMDS8EY7/n+mpOr+6eb8RXrppWuRHIqvnAgJE9BaYzLLESSo3n58rXTdlMrt2Wd1WCw41zWsQBPswnJNY5bCezm1GHyDW9/kmgDdZDV4vfCwqr+KJ53djEcWmLkcrP2hsXomvuvyY98JjcCm+3ZsfxFHzqMlbqYPDKozqEdlGdvZKlJCNPLzq+2N4ORK/w1RGBSPXZQ=="",""P"":null,""Q"":null,""DP"":null,""DQ"":null,""InverseQ"":null,""D"":null}")]
        public string RsaPublicKey {
            get {
                return ((string)(this["RsaPublicKey"]));
            }
            set {
                this["RsaPublicKey"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5028")]
        public int ID {
            get {
                return ((int)(this["ID"]));
            }
        }
    }
}
